<?php

/**
 * @file
 * Field module functionality for the File module.
 */

/**
 * Returns HTML for an individual note widget.
 *
 * @param $variables
 *   An associative array containing:
 *   - element: A render element representing the widget.
 *
 * @ingroup themeable
 */
function theme_note_widget_multiple($variables) {
    $element = $variables['element'];

    var_dump($element);

    $output = '';
    return $output;
}